### ISSUE TITLE
Correction in Readme + Suggestion

### ISSUE THREAD

**Issue by maxcurrent420** [blazickjp/GPT-CodeApp#17]
It looks like you have the configuration for Amazon AWS Bedrock models listed under the Anthropic config, and I don't see instructions on how to use this with Anthropic. 

Also, I found webAI-to-API that can use your browser cookie and interface with Claude without an official API key (which I don't have). I have no idea how or if I could configure something like this or other tools needing an API key to use a tool like WebAI-to-AI- so if you can make this work with the cookie like WebAI-to-AI, or integrate something like that into this, that would make it way more practical for me than anything I have found. 

This looks like a really cool project, so thanks for sharing it!

**Comment by blazickjp** [comment]
Yeah this is a good catch! I added support for Anthropic on Bedrock, not really Anthropic. I'll update the readme and maybe just enable use of any bedrock model. I was just excited that I could now use the Anthropic models haha.

I took a glance at the webAI-to-API and it looks super interesting. I'll have to dive deeper to understand how they're using the cookies, but yeah that would be awesome use that to enable the free versions of these products and eliminate the dependency on an API key to get started.

**Comment by maxcurrent420** [comment]
Oh thanks- I didn't realize Amazon hosted Anthropic's models! There's also an unofficial Claude API at GitHub.com/KoushikNavuluri/API that may be viable as well- hasn't had any changes in a few months but looks like it has some decent documentation might be easier to integrate it idk. Thanks for your contributions!

**Comment by blazickjp** [comment]
They just added Anthropic a couple few ago and Ive been pleasantly surprised with how good it is (also how different it is from GPT-4). Still need to do a lot to properly structure the prompts and support function calling. I imagine theres a lot of that code out there by now though.

Also, just because I've never really gotten any feedback yet, parts do you find most useful? What else would you want supported?

**Comment by maxcurrent420** [comment]
Well, from looking at the docs (haven't actually tried to run it without an OpenAI key) I like how it integrates the file operations and context management - I've seen MemGPT and "Sparse Priming Representations" mentioned as being good tools to help with the memory/context and I like that this aims to help with that and more. I appreciate the effort to make it configurable through the UI as well.

As for things to look out/reach for- I think there's been some tools come out that allow multiple "agents" to work together, taking on different roles, where one checks for errors etc. ChatDev comes to mind but seems to have limitations too. So I'm not sure if anyone has nailed it, but if you can have separate chats set up as agents and collaborate in a coordinated way, it could make the app that much more powerful.

Earlier this year I had lots of fun with a simple script I wrote to use a (no longer maintained) unofficial Poe API to have different models/agents carry on a conversation. Wasn't super useful, but interesting to send a prompt to a bot, have it respond to bot2, or even a third one, and back to bot1, x times, with them all having different personas or models. 

Of course some of the main issues there were memory/context and extra prompting to keep the conversation from degenerating into "Oh I'm an AI too! Let's talk about ourselves now..." were some of the main issues with that idea.

**Comment by blazickjp** [comment]
Thank you! I actually have a branch out there to integrate MemGPT into the Agent but that is going to take a bit more time. I think I saw someone wrote a FastAPI bakend using MemGPT so I may be able to use a lot of that work to get it up and running. SPR is another thing I'm thinking about a lot. Just really need to think through the best way to leverage SPR versions of information when tokens are sparse and full data when tokens are cheap. 

I have my eye on AutoGen and ChatDev. If I can figure out how to set them up as side processes, I'd like to use them as sub-agents for executing longer running tasks. Then the agent your chatting with doesn't need to do the work as it gets offloaded to the multi-agent group.

I also really like the idea of setting up separate chats as Agents where you can collaborate between them. That's a really interesting idea!
